import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
// import { AuthProvider } from "@/context/authContext.jsx"; // se agrego esto para seguridad 


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "APIMARKET",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* 👈 SOLUCIÓN */}
          {children}
        </AuthProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
